# Generated by Django 3.1.4 on 2021-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
