# Generated by Django 3.1.4 on 2021-01-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0003_ab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='level',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='tree_id',
        ),
    ]
