# Generated by Django 3.1.4 on 2021-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0005_remove_commentreply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
    ]
