# Generated by Django 3.1.4 on 2021-01-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0006_commentreply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
