# Generated by Django 3.1.4 on 2021-05-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0007_auto_20210130_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ab',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
