# Generated by Django 3.1.4 on 2021-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalidblog_app', '0008_auto_20210513_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='rand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
